FROM rust

# install protoc
RUN apt update && \
    apt install bash -y &&\
    apt install zsh -y &&\
    apt install curl -y &&\
    apt install git -y &&\
    apt install vim -y &&\
    apt install man -y &&\
    apt install fzf -y &&\
    echo end

WORKDIR /root/dotfiles